version: '3.0'

services:
  frontend:
    image: ghcr.io/jovanhyw/bootcamp-gds-frontend:c73b7bcb41ffb84e2409019968b2383004147167
    command: "npm start"
    environment:
      NODE_ENV: development
      APP_URL: http://localhost:3000
      API_URL: http://backend:3001
    ports:
      - 3000:3000
  
  backend:
    image: ghcr.io/jovanhyw/bootcamp-gds-backend:c73b7bcb41ffb84e2409019968b2383004147167
    command: "npm start"
    environment:
      NODE_ENV: development
      APP_URL: http://localhost:3000
      API_URL: http://localhost:3001
      PORT: 3001
    ports:
      - 3001:3001
